Target Java 8 for all plugins with -Werror compiler arg
PROBLEM:
Upgrading to Java 12 will cause the following innocuous warnings
to become build failures due to the "-Werror" flag:
```
> Task :connectivity:compileReleaseJavaWithJavac FAILED
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified
FAILURE: Build failed with an exception.
```
Example: https://github.com/WorldHealthOrganization/app/runs/1318596280

FIX:
Target Java 8 for all plugins that use the `-Werror` compiler argument:
```
android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

The plugins were all found with:
```
$ find . -name build.gradle | xargs grep Werror
./packages/connectivity/connectivity/android/build.gradle:def args = ["-Xlint:deprecation","-Xlint:unchecked","-Werror"]
./packages/camera/android/build.gradle:def args = ["-Xlint:deprecation","-Xlint:unchecked","-Werror"]
./packages/video_player/video_player/android/build.gradle:def args = ["-Xlint:deprecation","-Xlint:unchecked","-Werror"]
./packages/android_alarm_manager/android/build.gradle:def args = ["-Xlint:deprecation","-Xlint:unchecked","-Werror"]
./packages/android_intent/android/build.gradle:def args = ["-Xlint:deprecation","-Xlint:unchecked","-Werror"]
```
I think the config was broken for video_player. Also updated a few example apps too.

WORKAROUND:
As a temporary workaround, developers can downgrade to Java 11 which
doesn't warn that Java 7 is obsolete. Example:
https://github.com/WorldHealthOrganization/app/pull/1669/files#diff-710a4407aba47ffddf61ee9be9490428d5d0883759b18e490858db28e1ace4afR86

REGRESSION:
@hamdikahloun - thanks for your work on the Connectivity package. Adding `-Werror`
flags is a positive thing but I think is best combined with Java 8 to ensure that
the warning don't become error. Your PR: https://github.com/flutter/plugins/pull/3051

FYI @mehmetf, @Salakar, @bkonyi, @ened, @dnfield as you've all edited Java 8 targets