Prepare for change in handling of NoSuchMethod.
In a future release of Dart, if a class containing private members is
*implemented* (rather than *extendeed*), any attempt to invoke one of
the private members will result in a runtime error (see
https://github.com/dart-lang/sdk/issues/49687).  This is necessary in
order to soundly support field promotion
(https://github.com/dart-lang/language/issues/2020).

The runtime error will most likely be a new exception type, not
`NoSuchMethodError`.  So, to avoid breaking the
`SharedPreferencesStorePlatform.instance` setter, we need to
generalize it to consider any exception thrown by
`_verifyProvidesDefaultImplementations` as an indication that the
`SharedPreferencesStorePlatform` has been illegally implemented.

In the non-error case, `_verifyProvidesDefaultImplementations` does
nothing, so this generalization should be safe.